//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DoWork", ReplyAction="http://tempuri.org/IService1/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DoWork", ReplyAction="http://tempuri.org/IService1/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Data.DataTable GetData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Insert", ReplyAction="http://tempuri.org/IService1/InsertResponse")]
        bool Insert(int car_id, int obj_from_id, int obj_to_id, string date_from, string date_to);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Insert", ReplyAction="http://tempuri.org/IService1/InsertResponse")]
        System.Threading.Tasks.Task<bool> InsertAsync(int car_id, int obj_from_id, int obj_to_id, string date_from, string date_to);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSelectData", ReplyAction="http://tempuri.org/IService1/GetSelectDataResponse")]
        System.Data.DataTable GetSelectData(string tableName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSelectData", ReplyAction="http://tempuri.org/IService1/GetSelectDataResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetSelectDataAsync(string tableName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PrintConnectionInfo", ReplyAction="http://tempuri.org/IService1/PrintConnectionInfoResponse")]
        void PrintConnectionInfo(string name, string port, string path, string uri, string scheme);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PrintConnectionInfo", ReplyAction="http://tempuri.org/IService1/PrintConnectionInfoResponse")]
        System.Threading.Tasks.Task PrintConnectionInfoAsync(string name, string port, string path, string uri, string scheme);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PrintRowCount", ReplyAction="http://tempuri.org/IService1/PrintRowCountResponse")]
        void PrintRowCount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PrintRowCount", ReplyAction="http://tempuri.org/IService1/PrintRowCountResponse")]
        System.Threading.Tasks.Task PrintRowCountAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PrintError", ReplyAction="http://tempuri.org/IService1/PrintErrorResponse")]
        void PrintError(string error);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PrintError", ReplyAction="http://tempuri.org/IService1/PrintErrorResponse")]
        System.Threading.Tasks.Task PrintErrorAsync(string error);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WebClient.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WebClient.ServiceReference1.IService1>, WebClient.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public System.Data.DataTable GetData() {
            return base.Channel.GetData();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetDataAsync() {
            return base.Channel.GetDataAsync();
        }
        
        public bool Insert(int car_id, int obj_from_id, int obj_to_id, string date_from, string date_to) {
            return base.Channel.Insert(car_id, obj_from_id, obj_to_id, date_from, date_to);
        }
        
        public System.Threading.Tasks.Task<bool> InsertAsync(int car_id, int obj_from_id, int obj_to_id, string date_from, string date_to) {
            return base.Channel.InsertAsync(car_id, obj_from_id, obj_to_id, date_from, date_to);
        }
        
        public System.Data.DataTable GetSelectData(string tableName) {
            return base.Channel.GetSelectData(tableName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetSelectDataAsync(string tableName) {
            return base.Channel.GetSelectDataAsync(tableName);
        }
        
        public void PrintConnectionInfo(string name, string port, string path, string uri, string scheme) {
            base.Channel.PrintConnectionInfo(name, port, path, uri, scheme);
        }
        
        public System.Threading.Tasks.Task PrintConnectionInfoAsync(string name, string port, string path, string uri, string scheme) {
            return base.Channel.PrintConnectionInfoAsync(name, port, path, uri, scheme);
        }
        
        public void PrintRowCount() {
            base.Channel.PrintRowCount();
        }
        
        public System.Threading.Tasks.Task PrintRowCountAsync() {
            return base.Channel.PrintRowCountAsync();
        }
        
        public void PrintError(string error) {
            base.Channel.PrintError(error);
        }
        
        public System.Threading.Tasks.Task PrintErrorAsync(string error) {
            return base.Channel.PrintErrorAsync(error);
        }
    }
}
